apiVersion: apps/v1
kind: Deployment
metadata:
  name: i-yashdhanwantri-deployment
  labels:
    app: i-yashdhanwantri-develop
spec:
  template:
    metadata:
      name: i-yashdhanwantri-pod
      labels:
        app: i-yashdhanwantri-develop
        type: backend
    spec:
      containers:
        - name: i-yashdhanwantri-develop
          image: yashdhanwantri/i-yashdhanwantri-develop
  replicas: 3
  selector:
    matchLabels:
      app: i-yashdhanwantri-develop
      type: backend